### ISSUE TITLE
logos

### ISSUE THREAD

**Issue by EDiLD** [zsteinmetz/uniLDthesis#2]
Here are the logos that I used:

[Institute](https://github.com/EDiLD/edild.github.com/raw/master/files/logo_institut_pdf.pdf) and [University](https://github.com/EDiLD/edild.github.com/raw/master/files/uni_logo_farbig_pdf.pdf).

**Comment by zsteinmetz** [comment]
Thank you! I guess I closed #1 too early. I'll reopen #1 and close this one here ...
